### ISSUE TITLE
Doubts about montecarlo_python.py tests results

### ISSUE THREAD

**Issue by PawelGorny** [dickreuter/neuron_poker#19]
Hello
How do you know that expected test results are correct?
I have checked montecarlo_python.py file and tried to optimize a few things. One thing I do not like is removing cards from deck using pop(random(0, len(deck))) I have rewritten some pieces of code using just pop() from deque class, but then some test failed. My idea was to shuffle the deck and then just remove the cards one by one, instead of having ordered deck and removing random cards.
What I suspect, is that shuffle() method should receive a random seed... I must verify this. I have tried random and np.random but it is still failing.
You make take a look at branch 'opt' in my repo
BUT:
When I was reading original code, I found one piece which could probably not work as expected:
in distribute_cards_to_players in lines 169 & 170 you get random indexes,
`random_card1 = np.random.randint(0, len(deck))`
`random_card2 = np.random.randint(0, len(deck) - 1)`
 then in 173 you correctly get corresponding cards 
`self.get_two_short_notation([deck[random_card1], deck[random_card2]]`
but later you add cards to player's hand (and remove from deck in this same moment) using index, not the retrieved card:
`random_player.append(deck.pop(random_card1))`
`random_player.append(deck.pop(random_card2))`
Not, if for example random_card1=0 and random_card2=1, in line 173 you retrieve the cards for verification and in line 178 you retrieve the first card and remove from deck. Now indexes are switched, so your card random_card2 (=1) will give you a new card, not verified ( which originally had index=2).
The quick fix is to check indexes and first remove the card with bigger index. But after the fix, I started to get test failures too...
`assert 3.191379578251258 < 2`

**Comment by dickreuter** [comment]
The expected test results have been cross-referenced with other montecarlo simulators. If you have any doubt about specific cases, please check with some of the many free equity calculators that are available online or via iphone or android app.

I think the reason why I'm removing the card via index and not the removed card (it should be the same), is probably speed. But happy to change that if you have a more clean solution.

Ideally I would like to switch everything to the [numpy version](https://github.com/dickreuter/neuron_poker/blob/master/tools/montecarlo_numpy2.py), as it would be more than 1000 faster, but unfortunately, it's not yet correct, and also it doesn't have the ability to use ranges.

What's the problem with  pop(random(0, len(deck)))? You think it's not necessary to use random because the deck is already randomized? If so, then removing the random should not have any impact on the tests. If it does, then there are probably some unexpected side effects. Which test is failing exactly?

**Comment by PawelGorny** [comment]
Pop(index) on array is more expensive than pop() on deque. Some calls to len(array) are not needed and value could be replaced by variable. 
As I said - instead of retrieving and removing random elements (getting random number is an additional cost) I would shuffle the deck and then retrieve elements one by one.
The bug I mentioned allows two players to get this same card.

**Comment by dickreuter** [comment]
Sounds great. As long as the tests pass and it’s faster we should definitely implement that change.
